### ISSUE TITLE
Fields missing when branch is "master"

### ISSUE THREAD

**Issue by cuno** [dhilgarth/ReadGitVersionInformation#1]
When I had completed a pull request to merge to my master branch, multiple properties from `GitVersion.GetVersionInformation()` were suddenly an empty string. I can find the correct information in `GitVersionInformation.g.cs` but the information returned from `GitVersion.GetVersionInformation()` is incomplete. For example `Sha` and `BranchName` properties are empty.

When I created a test branch from my master branch, the information returned.

My GitVersion.yml:
```
mode: Mainline
branches: {}
ignore:
  sha: []
```

**Comment by dhilgarth** [comment]
Could you share that assembly? Privately is fine

**Comment by cuno** [comment]
Here you go.

https://drive.google.com/open?id=1ubS9ZvbgJ9DQsf_8ij5ZzDqWB_ElDdRK

**Comment by dhilgarth** [comment]
Thanks for sending me the assembly. The reason for the observed behavior is, that the `GitVersionInformation` class is not in the namespace it is supposed to be. In fact, it is not namespaced at all. According to [the documentation](https://gitversion.readthedocs.io/en/latest/usage/msbuild-task/) the class should be in the namespace with the same name as the assembly. However, I will now also support the no-namespace case --> #3   
So, I am a bit puzzled as to how you ended up with the assembly you did. What version of GitVersion are you using? Are you actually using the MSBuild task?

So, because the `GitVersionInformation` class couldn't be found, it is actually interpreting the `AssemblyInformationalVersion`. However, there is still a bug, if there no Prerelase label has been specified as is the case for your master branch --> #2

**Comment by dhilgarth** [comment]
I have pushed v1.0.1 to NuGet. This version should fix these issues. Please re-open if it doesn't.

**Comment by cuno** [comment]
v1.0.1 fixed my issues. Thank you for your quick response.
